= JAX-RS Analyzer
Sebastian Daschner

Generates an overview of all JAX-RS resources in a project by bytecode analysis.

*Yet another such JAX-RS tool?* +
Yes, but this gathers the information about the JAX-RS resource classes by bytecode analysis (not just by reflection).
This gains more information in several situations. You don't need additional annotations on your JAX-RS resource methods.
Using the JSR 339 standard is sufficient.

Java 8 is needed for the Analyzer.

== Maven Plugin

The Analyzer can be added to your project via https://github.com/sdaschner/jaxrs-analyzer-maven-plugin[Maven plugin].

== Swagger Backend

One of the output formats of the REST documentation is the heavily used Swagger API format. The tool creates the JSON file which can be loaded with Swagger UI.

== Standalone

Instead of using the Maven plugin, the tool can also run directly from the jar file. Therefore this project needs to be build with `mvn clean install`.
The executable jar file resides under `target/jaxrs-analyzer.jar`.
Run it with `java -jar jaxrs-analyzer.jar <basePathToYourCompiledClasses> [<backend>] [<projectName>] [<projectVersion>] [<deployedDomain>]`, e.g. `java -jar jaxrs-analyzer.jar ../yourProject/target/classes swagger`.
Currently supported backends are `swagger` (default), `asciidoc` and `plaintext`.

Feedback, bug reports and ideas for improvement are very welcome! Feel free to fork, comment, file an issue, etc. ;-)

For a current feature list see http://blog.sebastian-daschner.com/entries/jaxrs_analyzer_v0.2_feature_list[Feature list of JAX-RS Analyzer (v0.2)], http://blog.sebastian-daschner.com/entries/released_jaxrs_analyzer_v0.3[Released JAX-RS Analyzer v0.3] and http://blog.sebastian-daschner.com/entries/released_jaxrs_analyzer_v0.4[Released JAX-RS Analyzer v0.4].
